version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    docker:
    - image: cimg/base:stable
    steps:
    - checkout
    - node/install:
        install-yarn: true
        node-version: '18.14.2'
    - run:
        name: yarn install --frozen-lockfile
        command: yarn install --frozen-lockfile
    - run:
        name: yarn run build
        command: yarn run build
  deploy:
    docker:
    - image: cimg/base:stable
    steps:
    - run:
        name: Deploy over SSH
        command: |
          rsync -r dist $SSH_USER@$SSH_HOST:$SSH_WWWROOT/tetrominoes
workflows:
  build-and-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master

